name: Build and Test

on:
  push:
    branches: [ * ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Docker image
        run: docker build -t go-gin-project-template .
      - name: Run tests in Docker
        run: docker run go-gin-project-template go test ./... 